[project]
name = "python3_template"
version = "0.1.0"
description = "A python3 template using uv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "poethepoet>=0.38.0",
]




[tool.poe.tasks]
test = "python3 -m src.python3_template"

